/* automatically generated by rust-bindgen 0.72.1 */

pub type UInt8 = ::std::os::raw::c_uchar;
pub type UInt32 = ::std::os::raw::c_uint;
pub type SInt32 = ::std::os::raw::c_int;
pub type OSStatus = SInt32;
pub type FourCharCode = UInt32;
pub type OSType = FourCharCode;
pub type CFIndex = ::std::os::raw::c_long;
pub type CFTypeRef = *const ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __CFAllocator {
    _unused: [u8; 0],
}
pub type CFAllocatorRef = *const __CFAllocator;
unsafe extern "C" {
    pub static kCFAllocatorDefault: CFAllocatorRef;
}
unsafe extern "C" {
    pub fn CFRelease(cf: CFTypeRef);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __CFData {
    _unused: [u8; 0],
}
pub type CFDataRef = *const __CFData;
unsafe extern "C" {
    pub fn CFDataCreate(
        allocator: CFAllocatorRef,
        bytes: *const UInt8,
        length: CFIndex,
    ) -> CFDataRef;
}
unsafe extern "C" {
    pub fn CFDataGetLength(theData: CFDataRef) -> CFIndex;
}
unsafe extern "C" {
    pub fn CFDataGetBytePtr(theData: CFDataRef) -> *const UInt8;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __SecCertificate {
    _unused: [u8; 0],
}
pub type SecCertificateRef = *mut __SecCertificate;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __SecKeychain {
    _unused: [u8; 0],
}
pub type SecKeychainRef = *mut __SecKeychain;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __SecKeychainItem {
    _unused: [u8; 0],
}
pub type SecKeychainItemRef = *mut __SecKeychainItem;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __SecKeychainSearch {
    _unused: [u8; 0],
}
pub type SecKeychainSearchRef = *mut __SecKeychainSearch;
pub type SecKeychainAttrType = OSType;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SecKeychainAttribute {
    pub tag: SecKeychainAttrType,
    pub length: UInt32,
    pub data: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SecKeychainAttributeList {
    pub count: UInt32,
    pub attr: *mut SecKeychainAttribute,
}
unsafe extern "C" {
    pub fn SecKeychainOpen(
        pathName: *const ::std::os::raw::c_char,
        keychain: *mut SecKeychainRef,
    ) -> OSStatus;
}
unsafe extern "C" {
    pub fn SecKeychainAddGenericPassword(
        keychain: SecKeychainRef,
        serviceNameLength: UInt32,
        serviceName: *const ::std::os::raw::c_char,
        accountNameLength: UInt32,
        accountName: *const ::std::os::raw::c_char,
        passwordLength: UInt32,
        passwordData: *const ::std::os::raw::c_void,
        itemRef: *mut SecKeychainItemRef,
    ) -> OSStatus;
}
unsafe extern "C" {
    pub fn SecKeychainFindGenericPassword(
        keychainOrArray: CFTypeRef,
        serviceNameLength: UInt32,
        serviceName: *const ::std::os::raw::c_char,
        accountNameLength: UInt32,
        accountName: *const ::std::os::raw::c_char,
        passwordLength: *mut UInt32,
        passwordData: *mut *mut ::std::os::raw::c_void,
        itemRef: *mut SecKeychainItemRef,
    ) -> OSStatus;
}
pub type SecItemClass = FourCharCode;
unsafe extern "C" {
    pub fn SecKeychainItemModifyAttributesAndData(
        itemRef: SecKeychainItemRef,
        attrList: *const SecKeychainAttributeList,
        length: UInt32,
        data: *const ::std::os::raw::c_void,
    ) -> OSStatus;
}
unsafe extern "C" {
    pub fn SecKeychainItemFreeContent(
        attrList: *mut SecKeychainAttributeList,
        data: *mut ::std::os::raw::c_void,
    ) -> OSStatus;
}
unsafe extern "C" {
    pub fn SecKeychainItemDelete(itemRef: SecKeychainItemRef) -> OSStatus;
}
unsafe extern "C" {
    pub fn SecKeychainSearchCreateFromAttributes(
        keychainOrArray: CFTypeRef,
        itemClass: SecItemClass,
        attrList: *const SecKeychainAttributeList,
        searchRef: *mut SecKeychainSearchRef,
    ) -> OSStatus;
}
unsafe extern "C" {
    pub fn SecKeychainSearchCopyNext(
        searchRef: SecKeychainSearchRef,
        itemRef: *mut SecKeychainItemRef,
    ) -> OSStatus;
}
unsafe extern "C" {
    pub fn SecCertificateCreateWithData(
        allocator: CFAllocatorRef,
        data: CFDataRef,
    ) -> SecCertificateRef;
}
unsafe extern "C" {
    pub fn SecCertificateCopyData(certificate: SecCertificateRef) -> CFDataRef;
}
unsafe extern "C" {
    pub fn SecCertificateAddToKeychain(
        certificate: SecCertificateRef,
        keychain: SecKeychainRef,
    ) -> OSStatus;
}
