#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_DIR="$ROOT_DIR/tproxy_app"
SPEC_PATH="$APP_DIR/Project.yml"
DERIVED_DATA_PATH="${RAMA_TPROXY_DERIVED_DATA_PATH:-$ROOT_DIR/.xcode-derived/tproxy-app-dev}"
ISOLATE_CACHE="${RAMA_TPROXY_ISOLATED_CACHE:-0}"
HOME_DIR="${RAMA_TPROXY_HOME_DIR:-$HOME}"
TEAM_ID="${RAMA_TPROXY_DEVELOPMENT_TEAM:-ADPG6C355H}"
CONTAINER_SIGNING_IDENTITY="${RAMA_TPROXY_CONTAINER_SIGNING_IDENTITY:-Apple Development}"
EXT_SIGNING_IDENTITY="${RAMA_TPROXY_EXTENSION_SIGNING_IDENTITY:-$CONTAINER_SIGNING_IDENTITY}"
CONTAINER_PROFILE_SPECIFIER="${RAMA_TPROXY_CONTAINER_PROFILE_SPECIFIER:-}"
EXT_PROFILE_SPECIFIER="${RAMA_TPROXY_EXTENSION_PROFILE_SPECIFIER:-}"
BUILD_VERSION="${RAMA_TPROXY_CURRENT_PROJECT_VERSION:-$(date +%Y%m%d%H%M%S)}"
SKIP_CODESIGNING="${RAMA_TPROXY_SKIP_CODESIGNING:-0}"

cd "$APP_DIR"
mkdir -p "$DERIVED_DATA_PATH"
if [[ "$ISOLATE_CACHE" == "1" ]]; then
  mkdir -p "$HOME_DIR"
fi
xcodegen generate --spec "$SPEC_PATH"

cmd=(
  xcodebuild
  -project RamaTransparentProxyExample.xcodeproj
  -scheme RamaTransparentProxyExampleContainer
  -configuration Debug
  -derivedDataPath "$DERIVED_DATA_PATH"
  RAMA_TPROXY_CURRENT_PROJECT_VERSION="$BUILD_VERSION"
)

if [[ "$SKIP_CODESIGNING" == "1" ]]; then
  cmd+=(
    CODE_SIGNING_ALLOWED=NO
    CODE_SIGNING_REQUIRED=NO
    CODE_SIGN_STYLE=Manual
  )
else
  cmd+=(
    -allowProvisioningUpdates
    RAMA_TPROXY_DEVELOPMENT_TEAM="$TEAM_ID"
    RAMA_TPROXY_CONTAINER_SIGNING_IDENTITY="$CONTAINER_SIGNING_IDENTITY"
    RAMA_TPROXY_EXTENSION_SIGNING_IDENTITY="$EXT_SIGNING_IDENTITY"
  )

  if [[ -n "$CONTAINER_PROFILE_SPECIFIER" ]]; then
    cmd+=(RAMA_TPROXY_CONTAINER_PROFILE_SPECIFIER="$CONTAINER_PROFILE_SPECIFIER")
  fi
  if [[ -n "$EXT_PROFILE_SPECIFIER" ]]; then
    cmd+=(RAMA_TPROXY_EXTENSION_PROFILE_SPECIFIER="$EXT_PROFILE_SPECIFIER")
  fi
fi

cmd+=(clean build)
if [[ "$ISOLATE_CACHE" == "1" ]]; then
  env HOME="$HOME_DIR" \
    CFFIXED_USER_HOME="$HOME_DIR" \
    XDG_CACHE_HOME="$HOME_DIR/.cache" \
    CLANG_MODULE_CACHE_PATH="$DERIVED_DATA_PATH/ModuleCache.noindex" \
    SWIFT_MODULECACHE_PATH="$DERIVED_DATA_PATH/SwiftModuleCache" \
    "${cmd[@]}"
else
  "${cmd[@]}"
fi
