#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_DIR="$ROOT_DIR/tproxy_app"
SPEC_PATH="$APP_DIR/Project.yml"
DERIVED_DATA_PATH="${RAMA_TPROXY_DERIVED_DATA_PATH:-$ROOT_DIR/.xcode-derived/tproxy-app-dev}"
TEAM_ID="${RAMA_TPROXY_DEVELOPMENT_TEAM:-ADPG6C355H}"
HOST_SIGNING_IDENTITY="${RAMA_TPROXY_HOST_SIGNING_IDENTITY:-Apple Development}"
EXT_SIGNING_IDENTITY="${RAMA_TPROXY_EXTENSION_SIGNING_IDENTITY:-$HOST_SIGNING_IDENTITY}"
HOST_PROFILE_SPECIFIER="${RAMA_TPROXY_HOST_PROFILE_SPECIFIER:-}"
EXT_PROFILE_SPECIFIER="${RAMA_TPROXY_EXTENSION_PROFILE_SPECIFIER:-}"

cd "$APP_DIR"
xcodegen generate --spec "$SPEC_PATH"

cmd=(
  xcodebuild
  -project RamaTransparentProxyExample.xcodeproj
  -scheme RamaTransparentProxyExampleHost
  -configuration Debug
  -derivedDataPath "$DERIVED_DATA_PATH"
  -allowProvisioningUpdates
  RAMA_TPROXY_DEVELOPMENT_TEAM="$TEAM_ID"
  RAMA_TPROXY_HOST_SIGNING_IDENTITY="$HOST_SIGNING_IDENTITY"
  RAMA_TPROXY_EXTENSION_SIGNING_IDENTITY="$EXT_SIGNING_IDENTITY"
)

if [[ -n "$HOST_PROFILE_SPECIFIER" ]]; then
  cmd+=(RAMA_TPROXY_HOST_PROFILE_SPECIFIER="$HOST_PROFILE_SPECIFIER")
fi
if [[ -n "$EXT_PROFILE_SPECIFIER" ]]; then
  cmd+=(RAMA_TPROXY_EXTENSION_PROFILE_SPECIFIER="$EXT_PROFILE_SPECIFIER")
fi

cmd+=(clean build)
"${cmd[@]}"
