//! Whole-component setter surface on [`Uri`] — `set_*` / `with_*` /
//! `unset_*` / `without_*` (generated by `generate_set_and_with` plus
//! manual unset/without pairs for the byte-validated components).
//!
//! All setters auto-encode bytes outside the relevant RFC 3986
//! grammar, so the methods are infallible.

use super::parse_graceful;
use crate::Protocol;
use crate::address::{Authority, Domain, Host, HostWithOptPort, UserInfo};
use crate::uri::Uri;

// ----------------------------------------------------------------------
// Path
// ----------------------------------------------------------------------

#[test]
fn set_path_replaces_lazy_path() {
    let mut uri: Uri = parse_graceful("/old").unwrap();
    uri.set_path("/new");
    assert_eq!(uri.to_string(), "/new");
}

#[test]
fn set_path_preserves_query_and_fragment() {
    let mut uri: Uri = parse_graceful("/old?q=1#frag").unwrap();
    uri.set_path("/new");
    assert_eq!(uri.to_string(), "/new?q=1#frag");
}

#[test]
fn set_path_accepts_empty() {
    let mut uri: Uri = parse_graceful("https://example.com/x").unwrap();
    uri.set_path("");
    assert_eq!(uri.to_string(), "https://example.com");
}

#[test]
fn set_path_auto_encodes_query_and_fragment_bytes() {
    // `?` and `#` are encoded — to set the actual query/fragment,
    // use `set_query` / `set_fragment` separately.
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_path("/foo?bar");
    assert_eq!(uri.to_string(), "/foo%3Fbar");
    uri.set_path("/foo#frag");
    assert_eq!(uri.to_string(), "/foo%23frag");
}

#[test]
fn set_path_auto_encodes_controls_and_non_ascii() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_path("/foo\nbar");
    assert_eq!(uri.to_string(), "/foo%0Abar");
    uri.set_path("/foo\0bar");
    assert_eq!(uri.to_string(), "/foo%00bar");
    uri.set_path("/caf\u{e9}");
    assert_eq!(uri.to_string(), "/caf%C3%A9");
}

#[test]
fn set_path_passes_pchar_and_slash_through() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_path("/a/b/c-d.e_f~g!h$i&j'k(l)m*n+o,p;q=r:s@t/0123");
    assert_eq!(
        uri.to_string(),
        "/a/b/c-d.e_f~g!h$i&j'k(l)m*n+o,p;q=r:s@t/0123",
    );
}

#[test]
fn with_path_consumes_and_returns() {
    let uri = parse_graceful("/old").unwrap().with_path("/new");
    assert_eq!(uri.to_string(), "/new");
}

// ----------------------------------------------------------------------
// Query
// ----------------------------------------------------------------------

#[test]
fn set_query_replaces_and_adds() {
    let mut uri: Uri = parse_graceful("/p?old=1").unwrap();
    uri.set_query("new=2");
    assert_eq!(uri.to_string(), "/p?new=2");

    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_query("a=1");
    assert_eq!(uri.to_string(), "/p?a=1");
}

#[test]
fn set_query_empty_preserves_question_mark() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_query("");
    assert_eq!(uri.to_string(), "/p?");
}

#[test]
fn set_query_auto_encodes_hash() {
    // `#` would start a fragment — encoded so it stays in the query.
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_query("a=1#frag");
    assert_eq!(uri.to_string(), "/p?a=1%23frag");
}

#[test]
fn set_query_auto_encodes_controls_and_non_ascii() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_query("a=\n");
    assert_eq!(uri.to_string(), "/p?a=%0A");
    uri.set_query("city=caf\u{e9}");
    assert_eq!(uri.to_string(), "/p?city=caf%C3%A9");
}

#[test]
fn set_query_passes_query_grammar_through() {
    // Query allows `/` and `?` in addition to pchar.
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_query("a=1&b=2/3?4");
    assert_eq!(uri.to_string(), "/p?a=1&b=2/3?4");
}

#[test]
fn unset_query_removes_question_mark() {
    let mut uri: Uri = parse_graceful("/p?a=1").unwrap();
    uri.unset_query();
    assert_eq!(uri.to_string(), "/p");
    assert!(uri.query().is_none());
}

#[test]
fn without_query_consumes_and_removes() {
    let uri = parse_graceful("/p?a=1").unwrap().without_query();
    assert_eq!(uri.to_string(), "/p");
}

// ----------------------------------------------------------------------
// Fragment
// ----------------------------------------------------------------------

#[test]
fn set_fragment_replaces_and_empty_preserves_hash() {
    let mut uri: Uri = parse_graceful("/p#old").unwrap();
    uri.set_fragment("new");
    assert_eq!(uri.to_string(), "/p#new");

    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_fragment("");
    assert_eq!(uri.to_string(), "/p#");
}

#[test]
fn set_fragment_auto_encodes_controls_and_non_ascii() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.set_fragment("sec\n");
    assert_eq!(uri.to_string(), "/p#sec%0A");
}

#[test]
fn unset_and_without_fragment() {
    let mut uri: Uri = parse_graceful("/p#section").unwrap();
    uri.unset_fragment();
    assert_eq!(uri.to_string(), "/p");

    let uri = parse_graceful("/p#section").unwrap().without_fragment();
    assert_eq!(uri.to_string(), "/p");
}

// ----------------------------------------------------------------------
// Scheme & authority (typed, infallible — Option<T> macro variant)
// ----------------------------------------------------------------------

#[test]
fn scheme_set_unset_with_without_and_maybe() {
    let mut uri: Uri = parse_graceful("http://example.com/").unwrap();
    uri.set_scheme(Protocol::HTTPS);
    assert_eq!(uri.to_string(), "https://example.com/");
    uri.unset_scheme();
    assert_eq!(uri.to_string(), "//example.com/");

    let uri = parse_graceful("//example.com/p")
        .unwrap()
        .with_scheme(Protocol::HTTPS);
    assert_eq!(uri.to_string(), "https://example.com/p");
    let uri = uri.without_scheme();
    assert_eq!(uri.to_string(), "//example.com/p");
    let uri = uri.maybe_with_scheme(Some(Protocol::HTTP));
    assert_eq!(uri.to_string(), "http://example.com/p");
    let uri = uri.maybe_with_scheme(None);
    assert_eq!(uri.to_string(), "//example.com/p");
}

#[test]
fn authority_set_unset_with_without() {
    let mut uri: Uri = parse_graceful("https://old.com/p").unwrap();
    uri.set_authority(Authority {
        user_info: None,
        address: HostWithOptPort {
            host: Host::Name(Domain::try_from("new.com").unwrap()),
            port: Some(8080),
        },
    });
    assert_eq!(uri.to_string(), "https://new.com:8080/p");
    uri.unset_authority();
    assert_eq!(uri.to_string(), "https:/p");
}

#[test]
fn set_authority_with_userinfo_on_origin_form() {
    let uri = parse_graceful("/p")
        .unwrap()
        .with_authority(Authority {
            user_info: Some(UserInfo::try_from("u:p").unwrap()),
            address: HostWithOptPort {
                host: Host::Name(Domain::try_from("api.example.com").unwrap()),
                port: None,
            },
        })
        .with_scheme(Protocol::HTTPS);
    assert_eq!(uri.to_string(), "https://u:p@api.example.com/p");
}

// ----------------------------------------------------------------------
// Promotion semantics
// ----------------------------------------------------------------------

#[test]
fn set_path_on_asterisk_drops_asterisk() {
    let mut uri: Uri = parse_graceful("*").unwrap();
    assert!(uri.is_asterisk());
    uri.set_path("/x");
    assert!(!uri.is_asterisk());
    assert_eq!(uri.to_string(), "/x");
}

#[test]
fn chained_setters() {
    let mut uri: Uri = parse_graceful("/").unwrap();
    uri.set_path("/v2/users")
        .set_query("page=2")
        .set_fragment("results");
    assert_eq!(uri.to_string(), "/v2/users?page=2#results");
}

#[test]
fn fluent_with_chain() {
    let uri = parse_graceful("/")
        .unwrap()
        .with_path("/v2/users")
        .with_query("page=2")
        .with_fragment("results");
    assert_eq!(uri.to_string(), "/v2/users?page=2#results");
}

#[test]
fn second_mutation_does_not_re_promote() {
    let mut uri: Uri = parse_graceful("/p?a=1").unwrap();
    uri.set_path("/q");
    uri.set_query("b=2");
    assert_eq!(uri.to_string(), "/q?b=2");
}

#[test]
fn mutation_preserves_userinfo_round_trip() {
    let mut uri: Uri = parse_graceful("https://user:pw@example.com/old").unwrap();
    uri.set_path("/new");
    assert_eq!(uri.to_string(), "https://user:pw@example.com/new");
    assert_eq!(uri.userinfo().unwrap().as_str(), "user:pw");
}

#[test]
fn clone_after_mutation_is_independent() {
    let mut a: Uri = parse_graceful("/p?a=1").unwrap();
    a.set_path("/q");
    let b = a.clone();
    a.set_path("/r");
    assert_eq!(a.to_string(), "/r?a=1");
    assert_eq!(b.to_string(), "/q?a=1");
}

// ----------------------------------------------------------------------
// Fast-path: legal owned inputs move into storage without copying.
// ----------------------------------------------------------------------

#[test]
fn set_path_with_legal_string_moves_into_storage() {
    let mut uri: Uri = parse_graceful("/").unwrap();
    let s = "/some/legal/path".repeat(200); // 3 KB, all-pchar+/ → no encoding
    let s_ptr = s.as_ptr();
    uri.set_path(s);
    let new_ptr = uri.path().unwrap().as_bytes().as_ptr();
    assert_eq!(
        s_ptr, new_ptr,
        "Legal owned input should have moved without copying",
    );
}

#[test]
fn set_path_with_encodable_string_allocates_new_buffer() {
    // Input contains space → encoding needed → must allocate fresh.
    let mut uri: Uri = parse_graceful("/").unwrap();
    let s = String::from("/hello world");
    uri.set_path(s);
    assert_eq!(uri.to_string(), "/hello%20world");
}
