//! Setter / mutation surface on [`Uri`] — `try_set_*` / `set_*` /
//! `with_*` / `try_with_*` / `unset_*` / `without_*` (generated by
//! `generate_set_and_with` for component setters, plus manual unset
//! pairs for the byte-validated path/query/fragment).
//!
//! Pins the Lazy → Owned promotion, validation rules per component,
//! and round-trip via [`Display`](std::fmt::Display).

use super::parse_graceful;
use crate::Protocol;
use crate::address::{Authority, Domain, Host, HostWithOptPort, UserInfo};
use crate::uri::Uri;

// ----------------------------------------------------------------------
// Path
// ----------------------------------------------------------------------

#[test]
fn try_set_path_replaces_lazy_path() {
    let mut uri: Uri = parse_graceful("/old").unwrap();
    uri.try_set_path("/new").unwrap();
    assert_eq!(uri.to_string(), "/new");
}

#[test]
fn try_set_path_preserves_query_and_fragment() {
    let mut uri: Uri = parse_graceful("/old?q=1#frag").unwrap();
    uri.try_set_path("/new").unwrap();
    assert_eq!(uri.to_string(), "/new?q=1#frag");
}

#[test]
fn try_set_path_accepts_empty() {
    let mut uri: Uri = parse_graceful("https://example.com/x").unwrap();
    uri.try_set_path("").unwrap();
    assert_eq!(uri.to_string(), "https://example.com");
}

#[test]
fn try_set_path_rejects_question_mark_hash_and_controls() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.try_set_path("/foo?bar").unwrap_err();
    uri.try_set_path("/foo#frag").unwrap_err();
    uri.try_set_path("/foo\nbar").unwrap_err();
    uri.try_set_path("/foo\0bar").unwrap_err();
}

#[test]
fn try_with_path_consumes_and_returns() {
    let uri = parse_graceful("/old")
        .unwrap()
        .try_with_path("/new")
        .unwrap();
    assert_eq!(uri.to_string(), "/new");
}

// ----------------------------------------------------------------------
// Query
// ----------------------------------------------------------------------

#[test]
fn try_set_query_replaces_and_adds() {
    let mut uri: Uri = parse_graceful("/p?old=1").unwrap();
    uri.try_set_query("new=2").unwrap();
    assert_eq!(uri.to_string(), "/p?new=2");

    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.try_set_query("a=1").unwrap();
    assert_eq!(uri.to_string(), "/p?a=1");
}

#[test]
fn try_set_query_empty_preserves_question_mark() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.try_set_query("").unwrap();
    assert_eq!(uri.to_string(), "/p?");
}

#[test]
fn unset_query_removes_question_mark() {
    let mut uri: Uri = parse_graceful("/p?a=1").unwrap();
    uri.unset_query();
    assert_eq!(uri.to_string(), "/p");
    assert!(uri.query().is_none());
}

#[test]
fn without_query_consumes_and_removes() {
    let uri = parse_graceful("/p?a=1").unwrap().without_query();
    assert_eq!(uri.to_string(), "/p");
}

#[test]
fn try_set_query_rejects_hash_and_controls() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.try_set_query("a=1#frag").unwrap_err();
    uri.try_set_query("a=\n").unwrap_err();
}

// ----------------------------------------------------------------------
// Fragment
// ----------------------------------------------------------------------

#[test]
fn try_set_fragment_replaces_and_empty_preserves_hash() {
    let mut uri: Uri = parse_graceful("/p#old").unwrap();
    uri.try_set_fragment("new").unwrap();
    assert_eq!(uri.to_string(), "/p#new");

    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.try_set_fragment("").unwrap();
    assert_eq!(uri.to_string(), "/p#");
}

#[test]
fn unset_and_without_fragment() {
    let mut uri: Uri = parse_graceful("/p#section").unwrap();
    uri.unset_fragment();
    assert_eq!(uri.to_string(), "/p");

    let uri = parse_graceful("/p#section").unwrap().without_fragment();
    assert_eq!(uri.to_string(), "/p");
}

#[test]
fn try_set_fragment_rejects_controls() {
    let mut uri: Uri = parse_graceful("/p").unwrap();
    uri.try_set_fragment("sec\n").unwrap_err();
}

// ----------------------------------------------------------------------
// Scheme & authority (typed, infallible — full macro Option<T> variant)
// ----------------------------------------------------------------------

#[test]
fn scheme_set_unset_with_without_and_maybe() {
    let mut uri: Uri = parse_graceful("http://example.com/").unwrap();
    uri.set_scheme(Protocol::HTTPS);
    assert_eq!(uri.to_string(), "https://example.com/");
    uri.unset_scheme();
    assert_eq!(uri.to_string(), "//example.com/");

    // Consuming + maybe variants
    let uri = parse_graceful("//example.com/p")
        .unwrap()
        .with_scheme(Protocol::HTTPS);
    assert_eq!(uri.to_string(), "https://example.com/p");
    let uri = uri.without_scheme();
    assert_eq!(uri.to_string(), "//example.com/p");
    let uri = uri.maybe_with_scheme(Some(Protocol::HTTP));
    assert_eq!(uri.to_string(), "http://example.com/p");
    let uri = uri.maybe_with_scheme(None);
    assert_eq!(uri.to_string(), "//example.com/p");
}

#[test]
fn authority_set_unset_with_without() {
    let mut uri: Uri = parse_graceful("https://old.com/p").unwrap();
    uri.set_authority(Authority {
        user_info: None,
        address: HostWithOptPort {
            host: Host::Name(Domain::try_from("new.com").unwrap()),
            port: Some(8080),
        },
    });
    assert_eq!(uri.to_string(), "https://new.com:8080/p");
    uri.unset_authority();
    assert_eq!(uri.to_string(), "https:/p");
}

#[test]
fn set_authority_with_userinfo_on_origin_form() {
    let uri = parse_graceful("/p")
        .unwrap()
        .with_authority(Authority {
            user_info: Some(UserInfo::try_from("u:p").unwrap()),
            address: HostWithOptPort {
                host: Host::Name(Domain::try_from("api.example.com").unwrap()),
                port: None,
            },
        })
        .with_scheme(Protocol::HTTPS);
    assert_eq!(uri.to_string(), "https://u:p@api.example.com/p");
}

// ----------------------------------------------------------------------
// Promotion semantics
// ----------------------------------------------------------------------

#[test]
fn try_set_path_on_asterisk_drops_asterisk() {
    let mut uri: Uri = parse_graceful("*").unwrap();
    assert!(uri.is_asterisk());
    uri.try_set_path("/x").unwrap();
    assert!(!uri.is_asterisk());
    assert_eq!(uri.to_string(), "/x");
}

#[test]
fn chained_setters() {
    let mut uri: Uri = parse_graceful("/").unwrap();
    uri.try_set_path("/v2/users")
        .unwrap()
        .try_set_query("page=2")
        .unwrap()
        .try_set_fragment("results")
        .unwrap();
    assert_eq!(uri.to_string(), "/v2/users?page=2#results");
}

#[test]
fn fluent_with_chain() {
    let uri = parse_graceful("/")
        .unwrap()
        .try_with_path("/v2/users")
        .unwrap()
        .try_with_query("page=2")
        .unwrap()
        .try_with_fragment("results")
        .unwrap();
    assert_eq!(uri.to_string(), "/v2/users?page=2#results");
}

#[test]
fn second_mutation_does_not_re_promote() {
    let mut uri: Uri = parse_graceful("/p?a=1").unwrap();
    uri.try_set_path("/q").unwrap();
    uri.try_set_query("b=2").unwrap();
    assert_eq!(uri.to_string(), "/q?b=2");
}

#[test]
fn mutation_preserves_userinfo_round_trip() {
    let mut uri: Uri = parse_graceful("https://user:pw@example.com/old").unwrap();
    uri.try_set_path("/new").unwrap();
    assert_eq!(uri.to_string(), "https://user:pw@example.com/new");
    assert_eq!(uri.userinfo().unwrap().as_str(), "user:pw");
}

#[test]
fn clone_after_mutation_is_independent() {
    // Arc::make_mut clones on demand — verify the snapshot is intact.
    let mut a: Uri = parse_graceful("/p?a=1").unwrap();
    a.try_set_path("/q").unwrap();
    let b = a.clone();
    a.try_set_path("/r").unwrap();
    assert_eq!(a.to_string(), "/r?a=1");
    assert_eq!(b.to_string(), "/q?a=1");
}

// ----------------------------------------------------------------------
// Zero-copy ownership transfer — owned inputs move into BytesMut storage
// without allocating fresh bytes. Verified via pointer comparison.
// ----------------------------------------------------------------------

#[test]
fn try_set_path_with_string_moves_into_storage() {
    // String → BytesMut should be zero-copy (Vec<u8> → Bytes → BytesMut).
    let mut uri: Uri = parse_graceful("/").unwrap();
    let s = "/some/path".repeat(200); // 2 KB, large enough that re-allocation is detectable
    let s_ptr = s.as_ptr();
    uri.try_set_path(s).unwrap();
    let new_ptr = uri.path().unwrap().as_bytes().as_ptr();
    assert_eq!(
        s_ptr, new_ptr,
        "String contents should not have been copied"
    );
}
