# These are supported funding model platforms

github: plabayo
polar: plabayo
buy_me_a_coffee: plabayo
custom: ["https://www.paypal.com/donate/?hosted_button_id=P3KCGT2ACBVFE", "https://plabayo.threadless.com/"]
