[target.armv7-unknown-linux-gnueabi]
pre-build = [
    "apt update && apt install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi",
]

[target.armv7-unknown-linux-gnueabi.env]
passthrough = [
    "CC=arm-linux-gnueabi-gcc",
    "CXX=arm-linux-gnueabi-g++",
    "CMAKE_C_COMPILER=arm-linux-gnueabi-gcc",
    "CMAKE_CXX_COMPILER=arm-linux-gnueabi-g++",
    "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabi-gcc",
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "apt update && apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf",
]

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "CC=arm-linux-gnueabihf-gcc",
    "CXX=arm-linux-gnueabihf-g++",
    "CMAKE_C_COMPILER=arm-linux-gnueabihf-gcc",
    "CMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++",
    "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc",
]

[target.arm-unknown-linux-gnueabi]
pre-build = [
    "apt update && apt install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi",
]

[target.arm-unknown-linux-gnueabi.env]
passthrough = [
    "CC=arm-linux-gnueabi-gcc",
    "CXX=arm-linux-gnueabi-g++",
    "CMAKE_C_COMPILER=arm-linux-gnueabi-gcc",
    "CMAKE_CXX_COMPILER=arm-linux-gnueabi-g++",
    "CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabi-gcc",
]

[target.arm-unknown-linux-gnueabihf]
pre-build = [
    "apt update && apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf",
]

[target.arm-unknown-linux-gnueabihf.env]
passthrough = [
    "CC=arm-linux-gnueabihf-gcc",
    "CXX=arm-linux-gnueabihf-g++",
    "CMAKE_C_COMPILER=arm-linux-gnueabihf-gcc",
    "CMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++",
    "CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc",
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt update && apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu",
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "CC=aarch64-linux-gnu-gcc",
    "CXX=aarch64-linux-gnu-g++",
    "CMAKE_C_COMPILER=aarch64-linux-gnu-gcc",
    "CMAKE_CXX_COMPILER=aarch64-linux-gnu-g++",
    "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc",
]

[target.x86_64-pc-windows-gnu]
pre-build = [
    "apt update && apt install -y libclang-10-dev clang-10 cmake nasm gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64",
]

[target.x86_64-pc-windows-gnu.env]
passthrough = [
    "CC=x86_64-w64-mingw32-gcc",
    "CXX=x86_64-w64-mingw32-g++",
    "CMAKE_C_COMPILER=x86_64-w64-mingw32-gcc",
    "CMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++",
    "CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=x86_64-w64-mingw32-gcc",
    "BINDGEN_EXTRA_CLANG_ARGS=-idirafter/usr/include",
]

[target.i686-pc-windows-gnu]
pre-build = [
    "apt update && apt install -y libclang-10-dev clang-10 cmake nasm gcc-mingw-w64-i686 g++-mingw-w64-i686",
]

[target.i686-pc-windows-gnu.env]
passthrough = [
    "CC=i686-w64-mingw32-gcc",
    "CXX=i686-w64-mingw32-g++",
    "CMAKE_C_COMPILER=i686-w64-mingw32-gcc",
    "CMAKE_CXX_COMPILER=i686-w64-mingw32-g++",
    "CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER=i686-w64-mingw32-gcc",
    "BINDGEN_EXTRA_CLANG_ARGS=-idirafter/usr/include",
]
