[package]
name = "rama-rt-macros"
description = "macros in function of rama-rt"
readme = "README.md"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[features]

[dependencies]
proc-macro2 = "1.0.73"
quote = "1"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
rama = { version = "0.2", path = ".." }

[package.metadata.docs.rs]
all-features = true
