use std::hash::Hasher;

use rand::{Rng, RngExt};

use crate::proto::{ConfigError, Duration, MAX_CID_SIZE, shared::ConnectionId};

/// Generates connection IDs for incoming connections
pub trait ConnectionIdGenerator: Send + Sync {
    /// Generates a new CID
    ///
    /// Connection IDs MUST NOT contain any information that can be used by
    /// an external observer (that is, one that does not cooperate with the
    /// issuer) to correlate them with other connection IDs for the same
    /// connection. They MUST have high entropy, e.g. due to encrypted data
    /// or cryptographic-grade random data.
    fn generate_cid(&mut self) -> ConnectionId;

    /// Quickly determine whether `cid` could have been generated by this generator
    ///
    /// False positives are permitted, but increase the cost of handling invalid packets.
    fn validate(&self, _cid: &ConnectionId) -> Result<(), InvalidCid> {
        Ok(())
    }

    /// Returns the length of a CID for connections created by this generator
    fn cid_len(&self) -> usize;
    /// Returns the lifetime of generated Connection IDs
    ///
    /// Connection IDs will be retired after the returned `Duration`, if any. Assumed to be constant.
    fn cid_lifetime(&self) -> Option<Duration>;
}

/// How an endpoint makes a connection ID generator: one call per endpoint, so each has its
/// own state.
pub type ConnectionIdGeneratorFactory =
    std::sync::Arc<dyn Fn() -> Box<dyn ConnectionIdGenerator> + Send + Sync>;

rama_utils::macros::error::static_str_error! {
    #[doc = "connection ID was not recognized by the connection ID generator"]
    #[derive(Copy)]
    pub struct InvalidCid;
}

/// Generates purely random connection IDs of a specified length
///
/// Random CIDs can be smaller than those produced by [`HashedConnectionIdGenerator`], but cannot be
/// usefully [`validate`](ConnectionIdGenerator::validate)d.
#[derive(Debug, Clone, Copy)]
pub struct RandomConnectionIdGenerator {
    cid_len: usize,
    lifetime: Option<Duration>,
}

impl Default for RandomConnectionIdGenerator {
    fn default() -> Self {
        Self {
            cid_len: 8,
            lifetime: None,
        }
    }
}

impl RandomConnectionIdGenerator {
    /// A generator of identifiers `cid_len` bytes long, at most [`MAX_CID_SIZE`].
    ///
    /// Fails for a longer length, which QUIC has no room for (RFC 9000 §17.2).
    pub fn new(cid_len: usize) -> Result<Self, ConfigError> {
        if cid_len > MAX_CID_SIZE {
            return Err(ConfigError::OutOfBounds);
        }
        Ok(Self {
            cid_len,
            ..Self::default()
        })
    }

    /// A generator of identifiers of the longest size QUIC carries.
    #[must_use]
    pub fn of_max_size() -> Self {
        Self {
            cid_len: MAX_CID_SIZE,
            ..Self::default()
        }
    }

    rama_utils::macros::generate_set_and_with! {
        /// How long the identifiers this generator creates are used before they are retired.
        ///
        /// `None`, the default, retires them only when the peer or the protocol asks.
        pub fn lifetime(mut self, lifetime: Option<Duration>) -> Self {
            self.lifetime = lifetime;
            self
        }
    }
}

impl ConnectionIdGenerator for RandomConnectionIdGenerator {
    fn generate_cid(&mut self) -> ConnectionId {
        let mut bytes_arr = [0; MAX_CID_SIZE];
        rand::rng().fill_bytes(&mut bytes_arr[..self.cid_len]);

        ConnectionId::new(&bytes_arr[..self.cid_len])
    }

    /// Provide the length of dst_cid in short header packet
    fn cid_len(&self) -> usize {
        self.cid_len
    }

    fn cid_lifetime(&self) -> Option<Duration> {
        self.lifetime
    }
}

/// Generates 8-byte connection IDs that can be efficiently
/// [`validate`](ConnectionIdGenerator::validate)d
///
/// This generator uses a non-cryptographic hash and can therefore still be spoofed, but nonetheless
/// helps prevent the endpoint from responding to non-QUIC packets at very low cost.
pub struct HashedConnectionIdGenerator {
    key: u64,
    lifetime: Option<Duration>,
}

impl HashedConnectionIdGenerator {
    /// A generator with a random key, so its identifiers are recognised only by itself.
    #[must_use]
    pub fn new() -> Self {
        Self::from_key(rand::rng().random())
    }

    /// A generator with a key of your own.
    ///
    /// Endpoints given the same key recognise one another's identifiers through
    /// [`validate`](ConnectionIdGenerator::validate), which is what lets a restarted endpoint,
    /// or another endpoint of the same service, tell a connection of its own from noise.
    #[must_use]
    pub fn from_key(key: u64) -> Self {
        Self {
            key,
            lifetime: None,
        }
    }

    rama_utils::macros::generate_set_and_with! {
        /// How long the identifiers this generator creates are used before they are retired.
        ///
        /// `None`, the default, retires them only when the peer or the protocol asks.
        pub fn lifetime(mut self, lifetime: Option<Duration>) -> Self {
            self.lifetime = lifetime;
            self
        }
    }
}

impl Default for HashedConnectionIdGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl ConnectionIdGenerator for HashedConnectionIdGenerator {
    fn generate_cid(&mut self) -> ConnectionId {
        let mut bytes_arr = [0; NONCE_LEN + SIGNATURE_LEN];
        rand::rng().fill_bytes(&mut bytes_arr[..NONCE_LEN]);
        let mut hasher = rustc_hash::FxHasher::default();
        hasher.write_u64(self.key);
        hasher.write(&bytes_arr[..NONCE_LEN]);
        bytes_arr[NONCE_LEN..].copy_from_slice(&hasher.finish().to_le_bytes()[..SIGNATURE_LEN]);
        ConnectionId::new(&bytes_arr)
    }

    fn validate(&self, cid: &ConnectionId) -> Result<(), InvalidCid> {
        // An identifier this generator did not make can be any length a peer chose, including
        // none. Only one of its own can be recognised, so any other length is refused before
        // it is split.
        if cid.len() != NONCE_LEN + SIGNATURE_LEN {
            return Err(InvalidCid::new());
        }
        let (nonce, signature) = cid.split_at(NONCE_LEN);
        let mut hasher = rustc_hash::FxHasher::default();
        hasher.write_u64(self.key);
        hasher.write(nonce);
        let expected = hasher.finish().to_le_bytes();
        match expected[..SIGNATURE_LEN] == signature[..] {
            true => Ok(()),
            false => Err(InvalidCid::new()),
        }
    }

    fn cid_len(&self) -> usize {
        NONCE_LEN + SIGNATURE_LEN
    }

    fn cid_lifetime(&self) -> Option<Duration> {
        self.lifetime
    }
}

const NONCE_LEN: usize = 3; // Good for more than 16 million connections
const SIGNATURE_LEN: usize = 8 - NONCE_LEN; // 8-byte total CID length

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_keyed_cid() {
        let mut generator = HashedConnectionIdGenerator::new();
        let cid = generator.generate_cid();
        generator.validate(&cid).expect("its own identifier");
    }

    /// An identifier this generator did not make is refused, whatever length a peer gave it,
    /// including none and the longest QUIC carries. Only one of its own, under the key that
    /// made it, is recognised.
    #[test]
    fn a_hashed_generator_refuses_what_it_did_not_make() {
        const KEY: u64 = 0x1234_5678_9abc_def0;
        const OTHER_KEY: u64 = 0x0fed_cba9_8765_4321;
        let mut generator = HashedConnectionIdGenerator::from_key(KEY);
        let mine = generator.generate_cid();
        assert_eq!(mine.len(), generator.cid_len());
        HashedConnectionIdGenerator::from_key(KEY)
            .validate(&mine)
            .expect("a generator holding the same key recognises it");
        assert!(
            HashedConnectionIdGenerator::from_key(OTHER_KEY)
                .validate(&mine)
                .is_err(),
            "another key does not recognise it"
        );

        for length in [0usize, 1, 7, 9, MAX_CID_SIZE] {
            let other = ConnectionId::try_from_bytes(&vec![0x5a; length])
                .expect("a length within the maximum");
            assert!(
                HashedConnectionIdGenerator::from_key(KEY)
                    .validate(&other)
                    .is_err(),
                "an identifier of {length} bytes is not one this generator made"
            );
        }

        assert!(
            ConnectionId::try_from_bytes(&[0x5a; MAX_CID_SIZE + 1]).is_err(),
            "and nothing longer than the maximum can be built at all"
        );
    }

    /// A random generator issues the length it was built with, and refuses one QUIC has no
    /// room for.
    #[test]
    fn a_random_generator_issues_the_length_it_was_given() {
        for length in [0usize, 1, 8, MAX_CID_SIZE] {
            let mut generator =
                RandomConnectionIdGenerator::new(length).expect("a length within the maximum");
            assert_eq!(generator.cid_len(), length);
            assert_eq!(generator.generate_cid().len(), length);
            assert_eq!(generator.cid_lifetime(), None);
        }
        RandomConnectionIdGenerator::new(MAX_CID_SIZE + 1)
            .expect_err("a length past the maximum is refused");

        let lived = RandomConnectionIdGenerator::new(8)
            .expect("eight bytes is a length")
            .with_lifetime(Duration::from_secs(60));
        assert_eq!(lived.cid_lifetime(), Some(Duration::from_secs(60)));
        assert_eq!(lived.without_lifetime().cid_lifetime(), None);
    }
}
