[package]
name = "rama-quic-proto"
description = "QUIC wire types, codec and profiles for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "quic", "codec", "network", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["std"]
std = ["rama-core/std", "rama-utils/std"]
arbitrary = ["dep:arbitrary"]

[dependencies]
rama-core = { workspace = true }
rama-utils = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
arbitrary = { workspace = true, optional = true }

[lints]
workspace = true
