//! An example showing how to serve a ttRPC service with rama.
//!
//! ttRPC ("gRPC for low-memory environments") is the RPC protocol used by container
//! runtimes such as containerd and their plugins. Unlike gRPC it does not ride on HTTP/2, and `rama-ttrpc`
//! has no transport of its own: you bring the connection from any rama transport
//! (here `rama-tcp`) and hand the stream to a `ServerConnection`.
//!
//! The `Greeter` service is generated from `examples/proto/greeter.proto` by
//! `rama-ttrpc-build` (invoked from the workspace `build.rs` when the `ttrpc` feature is
//! enabled) and pulled in with [`rama::ttrpc::include_proto!`].
//!
//! # Run the example
//!
//! ```sh
//! cargo run -p rama-examples --bin ttrpc_server --features=ttrpc,tcp
//! ```
//!
//! The server listens on `127.0.0.1:62070`.
//!
//! # Call it from the shell
//!
//! ttRPC is a binary, length-prefixed protocol (not HTTP), so `curl` does not apply:
//! use a raw TCP tool such as `nc`. The request below calls
//! `Greeter/SayHello { name: "helloworld" }`; the ASCII strings are inline and only the
//! ttRPC framing and protobuf tags/lengths are `\x..` bytes. Keep stdin open briefly so
//! `nc` reads the reply back:
//!
//! ```sh
//! printf '\x00\x00\x00\x3a\x00\x00\x00\x01\x01\x00\x0a\x20rama.examples.greeter.v1.Greeter\x12\x08SayHello\x1a\x0c\x0a\x0ahelloworld' \
//!   | { cat; sleep 1; } | nc 127.0.0.1 62070 | xxd
//! ```
//!
//! The reply is a `HelloReply` frame ending in the ASCII text `Hello helloworld!`.
//!
//! The leading bytes are a 10-byte ttRPC header
//! (`len:u32 | stream_id:u32 | type:u8=1 Request | flags:u8`), followed by a protobuf
//! `Request { service=1, method=2, payload=3 }` whose `payload` is the `HelloRequest`.

#![expect(
    clippy::expect_used,
    reason = "example: panic-on-error is the standard pattern for demos"
)]

use rama::{
    net::address::SocketAddress,
    rt::Executor,
    tcp::server::TcpListener,
    telemetry::tracing::{
        self,
        level_filters::LevelFilter,
        subscriber::{EnvFilter, fmt, layer::SubscriberExt, util::SubscriberInitExt},
    },
    ttrpc::TtrpcServer,
};

/// ttRPC stubs generated from `examples/proto/greeter.proto`.
mod greeter {
    #![allow(
        unreachable_pub,
        clippy::all,
        clippy::pedantic,
        clippy::allow_attributes,
        reason = "generated ttRPC/prost stubs are exempt from rama's lints"
    )]
    // Generated by this crate's `build.rs` into `OUT_DIR/ttrpc/` (namespaced by RPC
    // flavour so it never collides with gRPC codegen of the same package name). This
    // prefixing is something we do manually in `build.rs`, so normally this would be
    // imported with `rama::ttrpc::include_proto!("rama.examples.greeter.v1")`
    rama::ttrpc::include_proto!("ttrpc/rama.examples.greeter.v1");
}

use greeter::{HelloReply, HelloRequest};

const ADDR: SocketAddress = SocketAddress::local_ipv4(62070);

#[tokio::main]
async fn main() {
    tracing::subscriber::registry()
        .with(fmt::layer())
        .with(
            EnvFilter::builder()
                .with_default_directive(LevelFilter::INFO.into())
                .from_env_lossy(),
        )
        .init();

    let server = TtrpcServer::new().register(greeter::Greeter(GreeterService));

    tracing::info!("ttRPC greeter server listening on {ADDR}");
    TcpListener::bind_address(ADDR, Executor::default())
        .await
        .expect("bind TCP listener")
        .serve(server)
        .await;
}

/// Our implementation of the generated `Greeter` service trait.
#[derive(Clone)]
struct GreeterService;

impl greeter::Greeter for GreeterService {
    async fn say_hello(&self, req: HelloRequest) -> rama::ttrpc::Result<HelloReply> {
        tracing::info!(name = %req.name, "say_hello");
        Ok(HelloReply {
            message: format!("Hello {}!", req.name),
        })
    }
}
