use proc_macro2::{Literal, Span, TokenStream};
use quote::quote;
use syn::{Data, DeriveInput, Fields, GenericArgument, PathArguments, Type};

use crate::utils::support_root_ts;

enum FieldKind {
    /// `Option<&'a T>`, borrowed, gathered via `downcast_ref`.
    Ref,
    /// `Option<Arc<T>>`, owned Arc clone, gathered via `cloned_downcast`.
    Arc,
}

pub(crate) fn expand(input: DeriveInput) -> syn::Result<TokenStream> {
    let DeriveInput {
        ident,
        generics,
        data,
        ..
    } = input;

    if generics.type_params().next().is_some() {
        return Err(syn::Error::new_spanned(
            &generics,
            "`#[derive(FromExtensions)]` does not support type parameters",
        ));
    }
    if generics.const_params().next().is_some() {
        return Err(syn::Error::new_spanned(
            &generics,
            "`#[derive(FromExtensions)]` does not support const parameters",
        ));
    }
    let lifetimes: Vec<_> = generics.lifetimes().collect();
    if lifetimes.len() > 1 {
        return Err(syn::Error::new_spanned(
            &generics,
            "`#[derive(FromExtensions)]` supports at most one lifetime parameter",
        ));
    }

    let fields = match &data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return Err(syn::Error::new_spanned(
                    &ident,
                    "`#[derive(FromExtensions)]` only supports structs with named fields",
                ));
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                &ident,
                "`#[derive(FromExtensions)]` can only be derived for structs",
            ));
        }
    };
    if fields.is_empty() {
        return Err(syn::Error::new_spanned(
            &ident,
            "`#[derive(FromExtensions)]` requires at least one field",
        ));
    }

    let root = support_root_ts("rama-core", None);

    // Per field: the inner extension type `T` (for the target set) and the
    // assignment expression downcasting the matching slot to the field type.
    let mut inners = Vec::with_capacity(fields.len());
    let mut accessors = Vec::with_capacity(fields.len());
    for (i, field) in fields.iter().enumerate() {
        let name = field
            .ident
            .as_ref()
            .expect("named field always has an ident");
        let (kind, inner) = classify_field(&field.ty).ok_or_else(|| {
            syn::Error::new_spanned(
                &field.ty,
                "every field must be `Option<&'a T>` or `Option<Arc<T>>`",
            )
        })?;
        let idx = Literal::usize_unsuffixed(i);
        let method = match kind {
            FieldKind::Ref => quote!(downcast_ref),
            FieldKind::Arc => quote!(cloned_downcast),
        };
        accessors.push(quote! {
            #name: out[#idx].and_then(#root::extensions::TypeErasedExtension::#method::<#inner>)
        });
        inners.push(inner);
    }

    let n = Literal::usize_unsuffixed(fields.len());
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();

    // The lifetime tying the borrowed slots to `ext`: reuse the struct's
    // lifetime if it has one, otherwise introduce a fresh one on the method
    // (a struct with only `Arc<T>` fields needs no lifetime of its own).
    let (fn_generics, lifetime) = if let Some(lt) = lifetimes.first() {
        (quote!(), quote!(#lt))
    } else {
        let fresh = syn::Lifetime::new("'__from_ext", Span::call_site());
        (quote!(<#fresh>), quote!(#fresh))
    };

    Ok(quote! {
        impl #impl_generics #ident #ty_generics #where_clause {
            /// Gather these extension pieces from `ext` in a single pass.
            ///
            /// Generated by `#[derive(FromExtensions)]`. Each field uses the
            /// same lookup as `Extensions::get_ref` (newest-wins, walks wrappers
            /// and the parent chain), but the store is traversed only once.
            pub fn from_extensions #fn_generics (
                ext: & #lifetime #root::extensions::Extensions,
            ) -> Self {
                let targets = [ #( ::core::any::TypeId::of::<#inners>() ),* ];
                let mut out: [
                    ::core::option::Option<& #lifetime #root::extensions::TypeErasedExtension>; #n
                ] = [::core::option::Option::None; #n];
                ext.get_many_erased(&targets, &mut out);
                Self { #( #accessors ),* }
            }
        }
    })
}

/// Classify a field as `Option<&'a T>` or `Option<Arc<T>>` and extract `T`.
fn classify_field(ty: &Type) -> Option<(FieldKind, &Type)> {
    match option_inner(ty)? {
        Type::Reference(reference) => Some((FieldKind::Ref, &reference.elem)),
        Type::Path(type_path) => {
            let segment = type_path.path.segments.last()?;
            if segment.ident != "Arc" {
                return None;
            }
            let PathArguments::AngleBracketed(args) = &segment.arguments else {
                return None;
            };
            let GenericArgument::Type(inner) = args.args.first()? else {
                return None;
            };
            Some((FieldKind::Arc, inner))
        }
        _ => None,
    }
}

/// Extract `T` from `Option<T>`.
fn option_inner(ty: &Type) -> Option<&Type> {
    let Type::Path(type_path) = ty else {
        return None;
    };
    let segment = type_path.path.segments.last()?;
    if segment.ident != "Option" {
        return None;
    }
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        return None;
    };
    let GenericArgument::Type(inner) = args.args.first()? else {
        return None;
    };
    Some(inner)
}
