#![allow(
    dead_code,
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    unreachable_pub,
    clippy::all
)]

// On Apple targets we use the bindgen output produced by build.rs. On non-Apple
// hosts running under `--cfg rama_docsrs` (i.e. our cross-platform doc build),
// we substitute a checked-in copy of that bindgen output so this module
// type-checks. None of the declarations are linkable; rustdoc only type-checks.
// The committed copy is regenerated by re-running bindgen on macOS — see
// build.rs for the input wrapper header and bindgen configuration.
#[cfg(target_vendor = "apple")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(all(rama_docsrs, not(target_vendor = "apple")))]
include!("_doc_ffi_stub.rs");
