[package]
name = "rama-icap"
description = "Internet Content Adaptation Protocol (ICAP) support for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
keywords = ["icap", "proxy", "async", "network", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-ios",
    "aarch64-linux-android",
]

[[example]]
name = "c_icap_oracle_server"
required-features = ["std"]

[features]
default = []
std = [
    "dep:rama-core",
    "dep:tokio",
    "rama-core/std",
    "rama-net/std",
    "rama-utils/std",
]

[dependencies]
rama-core = { workspace = true, optional = true }
rama-net = { workspace = true }
rama-utils = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros"], optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
