#!/usr/bin/env python3
"""Regenerate pylsqpack.tsv using the independent ls-qpack implementation.

python3 -m venv /tmp/rama-qpack-interop-venv
/tmp/rama-qpack-interop-venv/bin/pip install pylsqpack==0.3.22
/tmp/rama-qpack-interop-venv/bin/python path/to/this/generate_pylsqpack.py

The Rust fixture test requires no Python installation.
"""
import pathlib
import sys

import pylsqpack

assert pylsqpack.__version__ == "0.3.22", pylsqpack.__version__
output = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else
    pathlib.Path(__file__).with_name("pylsqpack.tsv"))
lines = ["# Generated by generate_pylsqpack.py using pylsqpack 0.3.22 (ls-qpack).",
         "# C: capacity, initial encoder stream. S: stream, encoder stream, section, blocked, name, value."]
for capacity in (64, 128, 256):
    encoder = pylsqpack.Encoder()
    decoder = pylsqpack.Decoder(capacity, 4)
    control = encoder.apply_settings(capacity, 4)
    decoder.feed_encoder(control)
    lines.append(f"C\t{capacity}\t{control.hex()}")
    for index in range(96):
        stream = 128 + 4 * index
        name = b"x-key"
        value = str(index // 3).encode()
        control, section = encoder.encode(stream, [(name, value)])
        # Intentionally deliver the field section before its encoder instructions.
        blocked = False
        try:
            feedback, fields = decoder.feed_header(stream, section)
        except pylsqpack.StreamBlocked:
            blocked = True
        unblocked = decoder.feed_encoder(control)
        if blocked:
            assert unblocked == [stream], unblocked
            feedback, fields = decoder.resume_header(stream)
        else:
            assert not unblocked
        assert fields == [(name, value)]
        encoder.feed_decoder(feedback)
        lines.append("\t".join(("S", str(stream), control.hex(), section.hex(),
                                str(int(blocked)), name.hex(), value.hex())))
output.write_text("\n".join(lines) + "\n")
