//! An example showing how to call a gRPC service generated from a `.proto` file.
//!
//! The service itself is defined in [`examples/proto/echo.proto`] and generated by this
//! crate's build script, see [`echo`] next to this example.
//!
//! Its sibling `grpc_json_echo` calls the very same `Echo` service without protobuf:
//! defined inline in Rust, with messages serialized as JSON. Run both to compare.
//!
//! # Run the example
//!
//! Start the server first:
//!
//! ```sh
//! cargo run -p rama-examples --bin grpc_echo_server --features=grpc,http-full
//! ```
//!
//! Then call it:
//!
//! ```sh
//! cargo run -p rama-examples --bin grpc_echo_client --features=grpc,http-full
//! ```
//!
//! [`examples/proto/echo.proto`]: https://github.com/plabayo/rama/blob/main/examples/proto/echo.proto

#![expect(
    clippy::print_stdout,
    reason = "example: print-for-output is the standard pattern for demos"
)]

use rama::{
    error::BoxError,
    http::{client::EasyHttpWebClient, grpc::Request},
    net::uri::Uri,
};

mod echo;
use echo::{EchoRequest, echo_client::EchoClient};

const ORIGIN: &str = "http://127.0.0.1:62072";

#[tokio::main]
async fn main() -> Result<(), BoxError> {
    let client = EchoClient::new(EasyHttpWebClient::default(), Uri::from_static(ORIGIN));

    let response = client
        .unary_echo(Request::new(EchoRequest {
            message: "hello rama".to_owned(),
        }))
        .await?;
    let message = response.into_inner().message;
    println!("unary echo: {message:?}");
    assert_eq!(message, "hello rama");

    let mut stream = client
        .server_streaming_echo(Request::new(EchoRequest {
            message: "hello rama".to_owned(),
        }))
        .await?
        .into_inner();
    let mut messages = Vec::new();
    while let Some(response) = stream.message().await? {
        println!("streaming echo: {:?}", response.message);
        messages.push(response.message);
    }
    assert_eq!(messages, ["hello", "rama"]);

    Ok(())
}
