//! The `Echo` service, generated from [`examples/proto/echo.proto`] by `rama-grpc-build`.
//!
//! This is the classic gRPC flow: a `.proto` file is the contract, a build script turns it
//! into Rust stubs and message types, and [`rama::http::grpc::include_proto!`] pulls those
//! into the crate.
//!
//! Use this when other languages talk to your service: they can generate their own code from
//! the same `.proto` file. You also get a compact wire format, and field numbers which keep
//! old and new versions compatible.
//!
//! The cost is that the messages are generated types. If you already have your own types,
//! you convert to and from them everywhere, and a Rust enum whose variants carry data has to
//! be modelled as a `oneof`. You also need `protoc` and a build step for every change.
//!
//! For the same service without any of that, see the `grpc_json_echo` example next to this
//! one: it defines the service in Rust and serializes your own types with serde.
//!
//! [`examples/proto/echo.proto`]: https://github.com/plabayo/rama/blob/main/examples/proto/echo.proto

#![allow(
    unreachable_pub,
    clippy::all,
    clippy::pedantic,
    clippy::allow_attributes,
    reason = "generated gRPC/prost stubs are exempt from rama's lints"
)]

// Generated by this crate's `build.rs` into `OUT_DIR/grpc/` (namespaced by RPC flavour so
// it never collides with ttRPC codegen of the same package name). This prefixing is
// something we do manually in `build.rs`, so normally this would be imported with
// `rama::http::grpc::include_proto!("rama.examples.echo.v1")`
rama::http::grpc::include_proto!("grpc/rama.examples.echo.v1");
