//! An example showing how to serve a gRPC service generated from a `.proto` file.
//!
//! The service itself is defined in [`examples/proto/echo.proto`] and generated by this
//! crate's build script, see [`echo`] next to this example.
//!
//! Its sibling `grpc_json_echo` serves the very same `Echo` service without protobuf:
//! defined inline in Rust, with messages serialized as JSON. Run both to compare.
//!
//! # Run the example
//!
//! ```sh
//! cargo run -p rama-examples --bin grpc_echo_server --features=grpc,http-full
//! ```
//!
//! The server listens on `127.0.0.1:62072`. Call it with the client example:
//!
//! ```sh
//! cargo run -p rama-examples --bin grpc_echo_client --features=grpc,http-full
//! ```
//!
//! [`examples/proto/echo.proto`]: https://github.com/plabayo/rama/blob/main/examples/proto/echo.proto

use rama::{
    error::BoxError,
    http::{
        grpc::{Request, Response, Status},
        server::HttpServer,
    },
    net::address::SocketAddress,
    rt::Executor,
    telemetry::tracing::{
        self,
        level_filters::LevelFilter,
        subscriber::{EnvFilter, fmt, layer::SubscriberExt, util::SubscriberInitExt},
    },
};

mod echo;
use echo::{EchoRequest, EchoResponse, echo_server};

const ADDR: SocketAddress = SocketAddress::local_ipv4(62072);

#[tokio::main]
async fn main() -> Result<(), BoxError> {
    tracing::subscriber::registry()
        .with(fmt::layer())
        .with(
            EnvFilter::builder()
                .with_default_directive(LevelFilter::INFO.into())
                .from_env_lossy(),
        )
        .init();

    tracing::info!("grpc echo server listening on {ADDR}");
    HttpServer::auto(Executor::default())
        .listen(ADDR, echo_server::EchoServer::new(EchoService))
        .await?;

    Ok(())
}

/// Our implementation of the generated `Echo` service trait.
struct EchoService;

impl echo_server::Echo for EchoService {
    /// Server streaming methods return a stream of their own, which the trait needs named.
    type ServerStreamingEchoStream =
        rama::stream::Iter<std::vec::IntoIter<Result<EchoResponse, Status>>>;

    async fn unary_echo(
        &self,
        request: Request<EchoRequest>,
    ) -> Result<Response<EchoResponse>, Status> {
        let message = request.into_inner().message;
        tracing::info!(%message, "unary_echo");
        Ok(Response::new(EchoResponse { message }))
    }

    async fn server_streaming_echo(
        &self,
        request: Request<EchoRequest>,
    ) -> Result<Response<Self::ServerStreamingEchoStream>, Status> {
        let message = request.into_inner().message;
        tracing::info!(%message, "server_streaming_echo");

        let messages: Vec<_> = message
            .split_whitespace()
            .map(|word| {
                Ok(EchoResponse {
                    message: word.to_owned(),
                })
            })
            .collect();

        Ok(Response::new(rama::stream::iter(messages)))
    }
}
