use super::utils;
use rama::net::address::HostWithPort;
use rama::net::client::{ConnectorService, EstablishedClientConnection, Request};
use rama::tcp::client::service::TcpConnector;
use rama::ttrpc::TtrpcConnector;
use std::time::Duration;

/// The same ttRPC stubs the example serves — here used to build a typed client.
mod greeter {
    #![allow(
        unreachable_pub,
        clippy::all,
        clippy::pedantic,
        clippy::allow_attributes,
        reason = "generated ttRPC/prost stubs are exempt from rama's lints"
    )]
    // Generated by this crate's `build.rs` into `OUT_DIR/ttrpc/` (namespaced by RPC flavour).
    rama::ttrpc::include_proto!("ttrpc/rama.examples.greeter.v1");
}
use greeter::{Greeter as _, HelloRequest};

#[tokio::test]
#[ignore]
async fn test_ttrpc_server() {
    utils::init_tracing();

    let _runner = utils::ExampleRunner::interactive("ttrpc_server", Some("ttrpc"));

    let connector = TtrpcConnector::new(TcpConnector::new());

    // the example server binds asynchronously; retry the connect until it is up
    let mut client = None;
    for i in 0..10u64 {
        match connector
            .connect(Request::new(HostWithPort::local_ipv4(62070)))
            .await
        {
            Ok(EstablishedClientConnection { conn, .. }) => {
                client = Some(conn);
                break;
            }
            Err(err) => {
                eprintln!("#{i}: connect to ttrpc example failed: {err}");
                tokio::time::sleep(Duration::from_millis(500 + 250 * i)).await;
            }
        }
    }
    let client = client.expect("connect to ttrpc example server");

    let reply = client
        .say_hello(HelloRequest {
            name: "world".to_owned(),
        })
        .await
        .expect("say_hello call should succeed");

    assert_eq!(reply.message, "Hello world!");
}
