name: Browserstack Fingerprinting

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

permissions:
  contents: read

jobs:
  run:
    timeout-minutes: 180
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd rama-fp/browserstack
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run your tests
        run: |
          cd rama-fp/browserstack
          python main.py
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          RAMA_FP_STORAGE_COOKIE: ${{ secrets.RAMA_FP_STORAGE_COOKIE }}
