name: Lambdatest Fingerprinting

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * 1"
jobs:
  run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        cd rama-fp/lambdatest
        npm ci
    - name: Run Playwright tests
      run: |
        cd rama-fp/lambdatest
        npx playwright test
