name: Build Rama CLI Releases
on:
  push:
    tags:
      - rama-*
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: true
        type: string
      build_docker:
        description: "Build Docker"
        required: true
        type: boolean
        default: true
      build_linux:
        description: "Build Linux"
        required: true
        type: boolean
        default: true
      build_macos:
        description: "Build macOS"
        required: true
        type: boolean
        default: true
      build_windows:
        description: "Build Windows"
        required: true
        type: boolean
        default: true

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

permissions:
  contents: read

jobs:
  build-release-linux:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_linux }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: true
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
          - name: x86_64-unknown-linux-musl
          - name: aarch64-unknown-linux-gnu
          - name: aarch64-unknown-linux-musl
          - name: armv7-unknown-linux-gnueabi
          - name: armv7-unknown-linux-gnueabihf
          - name: arm-unknown-linux-gnueabi
          - name: arm-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          targets: ${{ matrix.target.name }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          env-vars: "RUST_TOOLCHAIN=${{env.RUST_TOOLCHAIN}}"
          cache-bin: false

      - name: Install Zig
        if: contains(matrix.target.name, 'unknown-linux-musl')
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.13.0

      - name: Install cargo-zigbuild
        if: contains(matrix.target.name, 'unknown-linux-musl')
        run: cargo install --version 0.23.0 --locked cargo-zigbuild

      - name: Install cross
        if: contains(matrix.target.name, 'unknown-linux-musl') == false
        run: |
          cargo install --git https://github.com/cross-rs/cross --rev 1b8cf50d20180c1a394099e608141480f934b7f7 cross

      - name: Install bindgen-cli
        run: |
          cargo install --force --version 0.72.1 --locked bindgen-cli

      - name: Build release (musl)
        if: contains(matrix.target.name, 'unknown-linux-musl')
        timeout-minutes: 120
        run: |
          cargo zigbuild --release -p rama-cli --target "${{ matrix.target.name }}"

      - name: Build release (cross)
        if: contains(matrix.target.name, 'unknown-linux-musl') == false
        timeout-minutes: 120
        run: |
          cross build --release -p rama-cli --target "${{ matrix.target.name }}"

      - name: Package
        run: |
          cd target/${{ matrix.target.name }}/release && tar -cJf rama.${{ matrix.target.name }}.tar.xz rama

      - name: Generate checksums
        run: |
          cd target/${{ matrix.target.name }}/release
          sha256sum rama.${{ matrix.target.name }}.tar.xz > rama.${{ matrix.target.name }}.tar.xz.sha256

      - name: Upload Github Assets
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.target.name }}/release/*.tar.xz
            target/${{ matrix.target.name }}/release/*.sha256
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-release-macos:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_macos }}
    permissions:
      contents: write
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GNU tar
        if: runner.os == 'macOS'
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> "$GITHUB_PATH"

      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
        with:
          toolchain: ${{env.RUST_TOOLCHAIN}}
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          env-vars: "RUST_TOOLCHAIN=${{env.RUST_TOOLCHAIN}}"
          cache-bin: false

      - name: Build and Sign
        run: |
          bash ./rama-cli/scripts/build_and_sign_macos.sh "${{ matrix.target }}"
        env:
          MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
          MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          MACOS_CERT_COMMON_NAME: ${{ secrets.MACOS_CERT_COMMON_NAME }}
          AC_API_KEY_ID: ${{ secrets.AC_API_KEY_ID }}
          AC_API_ISSUER_ID: ${{ secrets.AC_API_ISSUER_ID }}
          AC_API_KEY: ${{ secrets.AC_API_KEY }}

      - name: Package
        run: |
          cd target/${{ matrix.target }}/release && tar -cJf rama.${{ matrix.target }}.tar.xz rama

      - name: Generate checksums
        run: |
          cd target/${{ matrix.target }}/release
          shasum -a 256 rama.${{ matrix.target }}.tar.xz > rama.${{ matrix.target }}.tar.xz.sha256

      - name: Upload Github Assets
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.target }}/release/*.tar.xz
            target/${{ matrix.target }}/release/*.sha256
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-release-windows:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_windows }}
    permissions:
      contents: write
    runs-on: windows-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2
      - uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          env-vars: "RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}"
          cache-bin: false

      - name: Build release (Windows)
        shell: bash
        run: |
          cargo build --release -p rama-cli --target ${{ matrix.target }}

      - name: upload-unsigned-artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: "target/${{ matrix.target }}/release/rama.exe"

      - id: optional_step_id
        uses: signpath/github-action-submit-signing-request@b9d91eadd323de506c0c81cf0c7fe7438f3360fd # v2
        with:
          api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
          organization-id: "177e81da-21f7-469e-823f-a924bcc9f474"
          project-slug: "rama"
          signing-policy-slug: "release-signing"
          github-artifact-id: "${{ steps.upload-unsigned-artifact.outputs.artifact-id }}"
          wait-for-completion: true
          output-artifact-directory: "target/${{ matrix.target }}/release"

      - name: Package (zip)
        shell: pwsh
        run: |
          $BinPath = "target/${{ matrix.target }}/release"
          $Exe     = Join-Path $BinPath "rama.exe"
          if (!(Test-Path $Exe)) { throw "Binary not found: $Exe" }
          $Zip = Join-Path $BinPath "rama.${{ matrix.target }}.zip"
          if (Test-Path $Zip) { Remove-Item $Zip }
          Compress-Archive -Path $Exe -DestinationPath $Zip -Force

      - name: Generate checksums
        shell: pwsh
        run: |
          $BinPath = "target/${{ matrix.target }}/release"
          $Zip     = Join-Path $BinPath "rama.${{ matrix.target }}.zip"
          $Hash    = (Get-FileHash -Path $Zip -Algorithm SHA256).Hash.ToLower()
          Set-Content -NoNewline -Path "$Zip.sha256" -Value "$Hash  $(Split-Path -Leaf $Zip)`n"

      - name: Upload Github Assets
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.target }}/release/*.zip
            target/${{ matrix.target }}/release/*.sha256
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-release-windows-arm:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_windows }}
    permissions:
      contents: write
    runs-on: windows-11-arm
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: true
      matrix:
        target:
          - aarch64-pc-windows-msvc

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2
      - uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          env-vars: "RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}"
          cache-bin: false

      - name: Build release (Windows)
        shell: bash
        run: |
          cargo build --release -p rama-cli --target ${{ matrix.target }}

      - name: upload-unsigned-artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: "target/${{ matrix.target }}/release/rama.exe"

      - id: optional_step_id
        uses: signpath/github-action-submit-signing-request@b9d91eadd323de506c0c81cf0c7fe7438f3360fd # v2
        with:
          api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
          organization-id: "177e81da-21f7-469e-823f-a924bcc9f474"
          project-slug: "rama"
          signing-policy-slug: "release-signing"
          github-artifact-id: "${{ steps.upload-unsigned-artifact.outputs.artifact-id }}"
          wait-for-completion: true
          output-artifact-directory: "target/${{ matrix.target }}/release"

      - name: Package (zip)
        shell: pwsh
        run: |
          $BinPath = "target/${{ matrix.target }}/release"
          $Exe     = Join-Path $BinPath "rama.exe"
          if (!(Test-Path $Exe)) { throw "Binary not found: $Exe" }
          $Zip = Join-Path $BinPath "rama.${{ matrix.target }}.zip"
          if (Test-Path $Zip) { Remove-Item $Zip }
          Compress-Archive -Path $Exe -DestinationPath $Zip -Force

      - name: Generate checksums
        shell: pwsh
        run: |
          $BinPath = "target/${{ matrix.target }}/release"
          $Zip     = Join-Path $BinPath "rama.${{ matrix.target }}.zip"
          $Hash    = (Get-FileHash -Path $Zip -Algorithm SHA256).Hash.ToLower()
          Set-Content -NoNewline -Path "$Zip.sha256" -Value "$Hash  $(Split-Path -Leaf $Zip)`n"

      - name: Upload Github Assets
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.target }}/release/*.zip
            target/${{ matrix.target }}/release/*.sha256
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  release-rama-cli-docker:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_docker }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: true
          tags: glendc/rama:latest,glendc/rama:${{ inputs.tag || github.ref_name }}
          file: rama-cli/infra/Dockerfile
